<?php
return array (
  2 => 
  array (
    'posid' => '2',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页头条推荐',
    'maxnum' => '20',
    'extention' => '{relation}',
    'listorder' => '4',
    'siteid' => '0',
    'thumb' => '',
  ),
  1 => 
  array (
    'posid' => '1',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页焦点图推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  41 => 
  array (
    'posid' => '41',
    'modelid' => '3',
    'catid' => '0',
    'name' => '中超频道头条小图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  40 => 
  array (
    'posid' => '40',
    'modelid' => '1',
    'catid' => '9',
    'name' => '中超频道头条推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  39 => 
  array (
    'posid' => '39',
    'modelid' => '1',
    'catid' => '15',
    'name' => '西甲频道热点资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  38 => 
  array (
    'posid' => '38',
    'modelid' => '1',
    'catid' => '15',
    'name' => '西甲频道球队相关资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  37 => 
  array (
    'posid' => '37',
    'modelid' => '3',
    'catid' => '0',
    'name' => '西甲频道头条小图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  36 => 
  array (
    'posid' => '36',
    'modelid' => '3',
    'catid' => '0',
    'name' => '西甲频道头条大图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  35 => 
  array (
    'posid' => '35',
    'modelid' => '1',
    'catid' => '15',
    'name' => '西甲频道头条推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  34 => 
  array (
    'posid' => '34',
    'modelid' => '3',
    'catid' => '0',
    'name' => '英超宝贝',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  33 => 
  array (
    'posid' => '33',
    'modelid' => '1',
    'catid' => '14',
    'name' => '英超频道热点资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  42 => 
  array (
    'posid' => '42',
    'modelid' => '3',
    'catid' => '0',
    'name' => '中超频道头条大图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  43 => 
  array (
    'posid' => '43',
    'modelid' => '1',
    'catid' => '9',
    'name' => '中超频道球队相关资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  44 => 
  array (
    'posid' => '44',
    'modelid' => '1',
    'catid' => '9',
    'name' => '中超频道热点资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  53 => 
  array (
    'posid' => '53',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页banner',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  52 => 
  array (
    'posid' => '52',
    'modelid' => '3',
    'catid' => '0',
    'name' => '法甲频道头条大图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  51 => 
  array (
    'posid' => '51',
    'modelid' => '3',
    'catid' => '0',
    'name' => '德甲频道头条大图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  50 => 
  array (
    'posid' => '50',
    'modelid' => '3',
    'catid' => '0',
    'name' => '意甲频道头条大图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  49 => 
  array (
    'posid' => '49',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页视频推荐',
    'maxnum' => '20',
    'extention' => '{timelen}',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  48 => 
  array (
    'posid' => '48',
    'modelid' => '3',
    'catid' => '0',
    'name' => '欧洲杯频道头条大图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  47 => 
  array (
    'posid' => '47',
    'modelid' => '3',
    'catid' => '0',
    'name' => '欧洲杯频道头条小图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  46 => 
  array (
    'posid' => '46',
    'modelid' => '1',
    'catid' => '12',
    'name' => '欧洲杯频道头条推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  45 => 
  array (
    'posid' => '45',
    'modelid' => '1',
    'catid' => '9',
    'name' => '中超频道球队资讯头条',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  32 => 
  array (
    'posid' => '32',
    'modelid' => '1',
    'catid' => '14',
    'name' => '英超频道球队相关资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  31 => 
  array (
    'posid' => '31',
    'modelid' => '3',
    'catid' => '0',
    'name' => '英超频道头条大图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  17 => 
  array (
    'posid' => '17',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频栏目精彩推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  16 => 
  array (
    'posid' => '16',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页每日热点',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  15 => 
  array (
    'posid' => '15',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页头条推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  14 => 
  array (
    'posid' => '14',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  12 => 
  array (
    'posid' => '12',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页图片推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  10 => 
  array (
    'posid' => '10',
    'modelid' => '0',
    'catid' => '0',
    'name' => '栏目首页推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  9 => 
  array (
    'posid' => '9',
    'modelid' => '0',
    'catid' => '0',
    'name' => '网站顶部推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  8 => 
  array (
    'posid' => '8',
    'modelid' => '3',
    'catid' => '20',
    'name' => '图片频道首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  5 => 
  array (
    'posid' => '5',
    'modelid' => '69',
    'catid' => '0',
    'name' => '推荐下载',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '1',
    'catid' => '0',
    'name' => '国际足球推荐图文',
    'maxnum' => '20',
    'extention' => '{keywords}',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '1',
    'catid' => '0',
    'name' => '中国足球推荐图文',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  30 => 
  array (
    'posid' => '30',
    'modelid' => '3',
    'catid' => '0',
    'name' => '英超频道头条小图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  29 => 
  array (
    'posid' => '29',
    'modelid' => '1',
    'catid' => '14',
    'name' => '英超频道头条推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  28 => 
  array (
    'posid' => '28',
    'modelid' => '1',
    'catid' => '17',
    'name' => '德甲推荐资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  27 => 
  array (
    'posid' => '27',
    'modelid' => '1',
    'catid' => '16',
    'name' => '意甲推荐资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '1',
    'catid' => '14',
    'name' => '英超推荐资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '1',
    'catid' => '15',
    'name' => '西甲推荐资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '1',
    'catid' => '13',
    'name' => '欧冠推荐资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '1',
    'catid' => '12',
    'name' => '欧洲杯推荐资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '1',
    'catid' => '0',
    'name' => '中国足球推荐资讯',
    'maxnum' => '20',
    'extention' => '{keywords}',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  13 => 
  array (
    'posid' => '13',
    'modelid' => '82',
    'catid' => '0',
    'name' => '栏目页焦点图',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>